### ISSUE TITLE
pip distribution package missed mkinc_utf8.mak file

### ISSUE THREAD

**Issue by elysium31** [snowballstem/pystemmer#40]
Got an error while installing with pip

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-g7ijdajv/pystemmer_f12c7427bc3a4c31a368b9d7e7fc3a36/setup.py", line 199, in <module>
    ['src/Stemmer.pyx'] + list(LIBRARY_SOURCE_CODE.source_code_paths()),
  File "/tmp/pip-install-g7ijdajv/pystemmer_f12c7427bc3a4c31a368b9d7e7fc3a36/setup.py", line 85, in source_code_paths
    for line in self.iter_manifest_lines():
  File "/tmp/pip-install-g7ijdajv/pystemmer_f12c7427bc3a4c31a368b9d7e7fc3a36/setup.py", line 74, in iter_manifest_lines
    with open(self.manifest_file_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'libstemmer_c-2.2.0/mkinc_utf8.mak'
```
I have checked pip's tar. For some reason it is located in libstemmer_c path, but not in libstemmer_c-2.2.0

**Comment by ojwb** [comment]
Thanks.  I think this is the same issue we're currently discussing in the (now unhelpfully titled) #37.

**Comment by HubTou** [comment]
Hello there.
Same issue whether installing or updating with pip.

**Comment by ojwb** [comment]
I've pushed a fix to git, but @felixonmars will need to make a new pypi release to deploy this.

Meanwhile I'd suggest the workaround of installing from git proposed above.

**Comment by ojwb** [comment]
2.2.0.1 is now on pypi.

**Comment by HubTou** [comment]
Works like a charm. Thank you guys!
