### ISSUE TITLE
pip install pystemmer

### ISSUE THREAD

**Issue by Cabu** [snowballstem/pystemmer#42]
Windows 10
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pystemmer
  Downloading PyStemmer-2.2.0.1.tar.gz (303 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.0/303.0 kB 585.6 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      Downloading https://snowballstem.org/dist/libstemmer_c-2.2.0.tar.gz... Traceback (most recent call last):
        File "C:\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "C:\Python\Python311\Lib\http\client.py", line 1286, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "C:\Python\Python311\Lib\http\client.py", line 1332, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "C:\Python\Python311\Lib\http\client.py", line 1281, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "C:\Python\Python311\Lib\http\client.py", line 1041, in _send_output
          self.send(msg)
        File "C:\Python\Python311\Lib\http\client.py", line 979, in send
          self.connect()
        File "C:\Python\Python311\Lib\http\client.py", line 1458, in connect
          self.sock = self._context.wrap_socket(self.sock,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
          return self.sslsocket_class._create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\ssl.py", line 1075, in _create
          self.do_handshake()
        File "C:\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\thier\AppData\Local\Temp\pip-install-owy6vr_b\pystemmer_345a507ab40e445fa467ecadf0ac198f\setup.py", line 126, in <module>
          LIBRARY_SOURCE_CODE.download()
        File "C:\Users\thier\AppData\Local\Temp\pip-install-owy6vr_b\pystemmer_345a507ab40e445fa467ecadf0ac198f\setup.py", line 110, in download
          download_and_extract_tarball(
        File "C:\Users\thier\AppData\Local\Temp\pip-install-owy6vr_b\pystemmer_345a507ab40e445fa467ecadf0ac198f\tarballfetcher.py", line 40, in download_and_extract_tarball
          download_file(tarball_url, tarball_filename)
        File "C:\Users\thier\AppData\Local\Temp\pip-install-owy6vr_b\pystemmer_345a507ab40e445fa467ecadf0ac198f\tarballfetcher.py", line 17, in download_file
          urlretrieve(url, filename)
        File "C:\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
                                  ^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 519, in open
          response = self._open(req, data)
                     ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 536, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ojwb** [comment]
The SSL certificate for https://snowballstem.org/ is managed by github - viewing it in firefox they seem to use letsencrypt and the certificate I get expires on Thu, 28 Dec 2023 04:36:57 GMT and appears to have been issued on Fri, 29 Sep 2023 04:36:58 GMT so I can't see how it was expired for you 2 days ago.

**Comment by ojwb** [comment]
Closing - I can successfully `pip install pystemmer` in a freshly created virtualenv, and as above the certificate is currently valid and the creation date suggests it was at the time of the report, so this seems to be a local configuration problem with https certificates on the reporter's system.
